export const CATEGORY = {
  EAT: {
    AMARICAN: 'American',
    ASIAN: 'Asian',
    BAKERY: 'Bakery',
    CHINESE: 'Chinese',
    EUROPEAN: 'European',
    FAST_FOOD: 'Fast Food',
    FRENCH: 'French',
    FUSION: 'Fusion',
    ITALIAN: 'Italian',
    JAPANESE: 'Japanese',
    KOREAN: 'Korean',
    LEBANESE: 'Lebanese',
    MIDDLE_EASTERN: 'Middle Eastern',
    MORDERN_NZ: 'Modern NZ',
    PIZZA: 'Pizza',
    PUB_FOOD: 'Pub Food',
    THAI: 'Thai',
    VEGETARIAN: 'Vegetarian',
    VIETNAMESE: 'Vietnamese',
  },
  DRINK: {
    BAR: 'Bar',
    BREWERY: 'Brewery',
    CAFE: 'Café',
    CLUB: 'Club',
    COCKTAIL_BAR: 'Cocktail Bar',
    CRAFT_BEER: 'Craft Beer',
    WINE_BAR: 'Wine Bar',
  },
  SEE: {
    AQUARIUM: 'Aquarium',
    ARCHITECTURE: 'Architecture',
    CHURCH: 'Church',
    GALLERY: 'Gallery',
    GARDEN: 'Garden',
    HISTORIC_BUILDING: 'Historic Building',
    MUSEUM: 'Museum',
    OBSERVATORY: 'Observatory',
    PARK: 'Park',
    SCULPTURE: 'Sculpture',
    SQUARE: 'Square',
    THEATRE: 'Theatre',
    TOWER: 'Tower',
    VIEWPOINT: 'Viewpoint',
    VOLCANO: 'Volcano',
    WINERY: 'Winery',
    ZOO: 'Zoo',
  },
  SHOP: {
    ARTS_AND_CRAFTS: 'Art & Crafts',
    BOOKS: 'Books',
    CLOTHING: 'Clothing',
    JEWELLERY: 'Jewellery',
    MARKET: 'Market',
    MUSIC: 'MUSIC',
    SHOPPING_CENTRE: 'Shopping Centre',
    SUPERMARKET: 'Supermarket',
  },
  SLEEP: {
    APARTMENT: 'Apartment',
    B_AND_B: 'B & B',
    CAMPGROUND: 'Campground',
    COTTAGE: 'Cottage',
    HOSTEL: 'Hostel',
    HOTEL: 'Hotel',
    MOTEL: 'Motel',
  },
  PLAY: {
    ADVENTURE_SPORTS: 'Adventure Sports',
    BOATING: 'Boating',
    CINEMA: 'Cinema',
    CLASSICAL_MUSIC: 'Classical Music',
    COMEDY: 'Comedy',
    CRUISE: 'Cruise',
    DIVING: 'Diving',
    KAYAKING: 'Kayaking',
    LIVE_MUSIC: 'Live Music',
    SCENIC_FLIGHTS: 'Senic Flights',
    SPECTATOR_SPORT: 'Spectator Sport',
    STADIUM: 'Stadium',
    SWIMMING: 'Swimming',
    THEATRE: 'Theatre',
    WALKING: 'Walking',
  },
};
